"""
Report Formatters - Renders Report objects as Markdown or JSON

Converts Report objects into human-readable Markdown or machine-readable JSON.
"""

from typing import Dict, List
import json
from datetime import datetime

from arcnical.schema import (
    Report, Recommendation, Severity, ArchitectureHealthScore
)


class MarkdownFormatter:
    """Formats Report as Markdown"""
    
    SEVERITY_EMOJI = {
        Severity.CRITICAL: "🔴",
        Severity.HIGH: "🟠",
        Severity.MEDIUM: "🟡",
        Severity.LOW: "🔵"
    }
    
    SEVERITY_BADGE = {
        Severity.CRITICAL: "**CRITICAL**",
        Severity.HIGH: "**HIGH**",
        Severity.MEDIUM: "**MEDIUM**",
        Severity.LOW: "**LOW**"
    }
    
    def format_report(self, report: Report) -> str:
        """
        Convert Report object to Markdown string.
        
        Args:
            report: Report object to format
            
        Returns:
            Formatted Markdown string
        """
        lines = []
        
        # Header
        lines.append("# Arcnical Architecture Review Report")
        lines.append("")
        lines.append(f"**Repository:** {report.summary.repo}")
        lines.append(f"**Analysis Date:** {report.metadata.generated_at.strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append(f"**Arcnical Version:** {report.metadata.tool_version}")
        lines.append("")
        
        # Health Score Section
        lines.extend(self._format_health_score(report.scores))
        lines.append("")

        # Executive Summary
        lines.append("## Executive Summary")
        lines.append("")
        lines.append(f"Total findings: **{len(report.recommendations)}**")
        lines.append("")
        
        # Findings by Severity
        lines.extend(self._format_findings_summary(report.recommendations))
        lines.append("")
        
        # Metrics
        if report.metrics:
            lines.append("## Metrics")
            lines.append("")
            lines.extend(self._format_metrics_table(report.metrics))
            lines.append("")
        
        # Findings by Layer
        lines.append("## Findings by Layer")
        lines.append("")
        
        layers = {}
        for rec in report.recommendations:
            if rec.layer not in layers:
                layers[rec.layer] = []
            layers[rec.layer].append(rec)
        
        for layer in ["L2", "L3", "SECURITY"]:
            if layer in layers:
                lines.extend(self._format_layer_findings(layer, layers[layer]))
                lines.append("")
        
        # Recommendations
        lines.append("## Recommendations")
        lines.append("")
        lines.append("**Prioritized by severity:**")
        lines.append("")
        
        for i, rec in enumerate(report.recommendations, 1):
            lines.append(f"{i}. {self.SEVERITY_EMOJI.get(rec.severity, '❓')} "
                        f"{rec.title}")
            if rec.suggested_action:
                lines.append(f"   - Action: {rec.suggested_action}")
        
        lines.append("")
        
        # Metadata Footer
        lines.append("---")
        lines.append("")
        lines.append(f"*Generated by Arcnical {report.metadata.tool_version} "
                    f"on {report.metadata.generated_at.strftime('%Y-%m-%d')}*")
        
        return "\n".join(lines)
    
    def _format_health_score(self, score: ArchitectureHealthScore) -> List[str]:
        """Format health score section"""
        lines = []
        
        # Overall score indicator
        if score.overall >= 80:
            indicator = "🟢 Excellent"
        elif score.overall >= 60:
            indicator = "🟡 Good"
        elif score.overall >= 40:
            indicator = "🟠 Fair"
        else:
            indicator = "🔴 Poor"
        
        lines.append("## Architecture Health Score")
        lines.append("")
        lines.append(f"**Overall: {score.overall}/100** {indicator}")
        lines.append("")
        lines.append("| Component | Score |")
        lines.append("|-----------|-------|")
        lines.append(f"| Maintainability | {score.maintainability}/100 |")
        lines.append(f"| Structure | {score.structure}/100 |")
        lines.append(f"| Security | {score.security}/100 |")
        
        return lines
    
    def _format_findings_summary(self, recommendations: List[Recommendation]) -> List[str]:
        """Format findings summary by severity"""
        lines = []
        
        severity_counts = {
            Severity.CRITICAL: 0,
            Severity.HIGH: 0,
            Severity.MEDIUM: 0,
            Severity.LOW: 0
        }
        
        for rec in recommendations:
            severity_counts[rec.severity] += 1
        
        lines.append("### Issues Found")
        lines.append("")
        lines.append(f"- 🔴 Critical: **{severity_counts[Severity.CRITICAL]}**")
        lines.append(f"- 🟠 High: **{severity_counts[Severity.HIGH]}**")
        lines.append(f"- 🟡 Medium: **{severity_counts[Severity.MEDIUM]}**")
        lines.append(f"- 🔵 Low: **{severity_counts[Severity.LOW]}**")
        
        return lines
    
    def _format_metrics_table(self, metrics) -> List[str]:
        """Format metrics as table"""
        lines = []
        
        lines.append("| Metric | Value | Status |")
        lines.append("|--------|-------|--------|")
        
        # Complexity
        if metrics.complexity_avg:
            status = "🟢 Good" if metrics.complexity_avg < 10 else "🟡 Moderate" if metrics.complexity_avg < 15 else "🔴 High"
            lines.append(f"| Average Complexity | {metrics.complexity_avg:.1f} | {status} |")
        
        # Instability
        if metrics.instability_avg:
            status = "🟢 Stable" if metrics.instability_avg < 0.5 else "🟡 Moderate" if metrics.instability_avg < 0.8 else "🔴 Unstable"
            lines.append(f"| Average Instability | {metrics.instability_avg:.2f} | {status} |")
        
        # Circular Dependencies
        if metrics.circular_dependency_count:
            status = "🟢 None" if metrics.circular_dependency_count == 0 else "🟡 Some" if metrics.circular_dependency_count < 5 else "🔴 Many"
            lines.append(f"| Circular Dependencies | {metrics.circular_dependency_count} | {status} |")
        
        # God Classes
        if metrics.god_class_count:
            status = "🟢 None" if metrics.god_class_count == 0 else "🟡 Few" if metrics.god_class_count < 3 else "🔴 Many"
            lines.append(f"| God Classes | {metrics.god_class_count} | {status} |")
        
        return lines
    
    def _format_layer_findings(self, layer: str, findings: List[Recommendation]) -> List[str]:
        """Format findings for a specific layer"""
        lines = []
        
        layer_name = {
            "L2": "L2 - Structural Issues",
            "L3": "L3 - Code Quality",
            "SECURITY": "Security"
        }.get(layer, layer)
        
        lines.append(f"### {layer_name}")
        lines.append("")
        
        if not findings:
            lines.append("✅ No issues found")
            return lines
        
        for finding in findings:
            lines.append(f"#### {self.SEVERITY_EMOJI.get(finding.severity, '❓')} {finding.title}")
            lines.append("")
            lines.append(f"**Severity:** {self.SEVERITY_BADGE.get(finding.severity, 'UNKNOWN')}")
            lines.append("")
            
            if finding.evidence:
                lines.append("**Evidence:**")
                if hasattr(finding.evidence, 'metric'):
                    lines.append(f"- Metric: {finding.evidence.metric}")
                    lines.append(f"- Value: {finding.evidence.value}")
                lines.append("")
            
            if finding.rationale:
                lines.append(f"**Rationale:** {finding.rationale}")
                lines.append("")
            
            if finding.suggested_action:
                lines.append(f"**Recommendation:** {finding.suggested_action}")
                lines.append("")
        
        return lines


class JSONFormatter:
    """Formats Report as JSON"""
    
    def format_report(self, report: Report) -> str:
        """
        Convert Report object to JSON string.
        
        Args:
            report: Report object to format
            
        Returns:
            Formatted JSON string
        """
        # Convert Pydantic model to dict
        report_dict = report.model_dump(
            mode='json',
            exclude_none=True
        )
        
        # Pretty-print JSON
        json_str = json.dumps(report_dict, indent=2, default=str)
        
        return json_str
    
    def format_report_compact(self, report: Report) -> str:
        """
        Convert Report to compact JSON (single line).
        
        Args:
            report: Report object to format
            
        Returns:
            Compact JSON string
        """
        report_dict = report.model_dump(
            mode='json',
            exclude_none=True
        )
        
        return json.dumps(report_dict, default=str)
